"""schema inicial: watch, listing, price_reading, coupon, publication

Revision ID: 697b919c6a1f
Revises: 
Create Date: 2026-09-23 10:26:25.475168

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '697b919c6a1f'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('regra_texto', sa.Text(), nullable=False),
    sa.Column('valido_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('testado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("marketplace IN ('shopee', 'aliexpress', 'mercado_livre', 'amazon')", name='ck_coupon_marketplace'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=False),
    sa.Column('referencia_fabricante', sa.String(length=120), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=False),
    sa.Column('tipo_movimento', sa.String(length=20), nullable=False),
    sa.Column('tamanho_caixa_mm', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('vigilancia_ativa', sa.Boolean(), nullable=False),
    sa.Column('preco_alvo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('exige_loja_oficial', sa.Boolean(), nullable=False),
    sa.Column('exige_reputacao_minima', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo_movimento IN ('automatico', 'quartzo', 'manual', 'solar', 'hibrido')", name='ck_watch_tipo_movimento'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean')
    )
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('marketplace_item_id', sa.String(length=120), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("marketplace IN ('shopee', 'aliexpress', 'mercado_livre', 'amazon')", name='ck_listing_marketplace'),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'marketplace_item_id', name='uq_listing_marketplace_item')
    )
    op.create_table('price_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('coletado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preco_vista', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('preco_parcelado_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parcelas', sa.Integer(), nullable=True),
    sa.Column('frete', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('moeda', sa.CHAR(length=3), nullable=False),
    sa.Column('em_estoque', sa.Boolean(), nullable=False),
    sa.Column('vendedor_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_loja_oficial', sa.Boolean(), nullable=True),
    sa.Column('origem', sa.String(length=60), nullable=False),
    sa.Column('desatualizado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'coletado_em', name='uq_price_reading_listing_coletado')
    )
    op.create_index('ix_price_reading_listing_coletado_desc', 'price_reading', ['listing_id', sa.literal_column('coletado_em DESC')], unique=False)
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preco_vista_publicado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('preco_efetivo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loja', sa.String(length=60), nullable=False),
    sa.Column('link_publicado', sa.Text(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('encerrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication')
    op.drop_index('ix_price_reading_listing_coletado_desc', table_name='price_reading')
    op.drop_table('price_reading')
    op.drop_table('listing')
    op.drop_table('watch')
    op.drop_table('coupon')
    # ### end Alembic commands ###
