"""candidato do motor de regras (RF15, RF16)

Revision ID: c5e8a1d9f2b3
Revises: a3c1f0d2b7e4
Create Date: 2026-09-26 20:42:51.540409

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5e8a1d9f2b3"
down_revision: str | None = "a3c1f0d2b7e4"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("watch_id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("coupon_id", sa.Integer(), nullable=True),
        sa.Column("regra", sa.String(length=20), nullable=False),
        sa.Column("preco_vista", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("desconto", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("preco_sem_frete", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("frete", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("frete_desconhecido", sa.Boolean(), nullable=False),
        sa.Column("media_30d", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("minimo_90d", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("preco_alvo", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("queda_percentual", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("economia_absoluta", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("pontuacao", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("decidido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decidido_por", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "regra IN ('media_30d', 'minimo_90d', 'preco_alvo')", name="ck_candidate_regra"
        ),
        sa.CheckConstraint(
            "status IN ('pendente', 'aprovado', 'descartado')", name="ck_candidate_status"
        ),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["coupon.id"],
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listing.id"],
        ),
        sa.ForeignKeyConstraint(
            ["watch_id"],
            ["watch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_candidate_watch_criado_desc",
        "candidate",
        ["watch_id", sa.literal_column("criado_em DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_candidate_watch_criado_desc", table_name="candidate")
    op.drop_table("candidate")
    # ### end Alembic commands ###
