"""texto da publicacao (RF20, RF22, RF30)

Revision ID: d3694707da3e
Revises: c5e8a1d9f2b3
Create Date: 2026-09-28 09:21:09.051172

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3694707da3e"
down_revision: str | None = "c5e8a1d9f2b3"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publication", sa.Column("texto_publicado", sa.Text(), nullable=False))
    op.add_column(
        "publication",
        sa.Column("texto_editado", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publication", "texto_editado")
    op.drop_column("publication", "texto_publicado")
    # ### end Alembic commands ###
